# Generated by Django 5.0.6 on 2024-05-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Aeroppp", "0003_remove_engineer_manager_assigned_engineermanager_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="engineer",
            name="availability",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="engineer",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
