# Generated by Django 5.0.6 on 2024-06-15 15:00

from django.db import migrations

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("Aeroppp", "0006_task_created_at_task_deadline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="task",
            name="deadline",
        ),
    ]
