# Generated by Django 5.0.6 on 2024-06-15 15:28

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Aeroppp", "0007_remove_task_created_at_remove_task_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 15, 15, 27, 56, 352176, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
