# Generated by Django 5.0.6 on 2024-06-15 15:41

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):
    dependencies = [
        ("Aeroppp", "0010_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(default = timezone.now),
        ),
    ]
