# Generated by Django 5.0.6 on 2024-06-15 17:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Aeroppp", "0011_alter_task_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="progress",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 18, 17, 34, 39, 571777, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
