# Generated by Django 5.0.6 on 2024-06-18 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Aeroppp", "0014_alter_task_deadline_chatmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 21, 22, 20, 52, 8055, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
