# Generated by Django 5.0.6 on 2024-06-19 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Aeroppp", "0016_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 22, 9, 0, 48, 154356, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
