# Generated by Django 5.0.6 on 2024-06-26 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Aeroppp", "0019_alter_task_deadline_tasknotification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 29, 21, 48, 2, 867767, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
