# Generated by Django 5.0.6 on 2024-06-28 13:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Aeroppp", "0022_alter_task_deadline_taskprogressnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskprogressnotification",
            name="engineer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Aeroppp.engineer",
            ),
        ),
        migrations.AddField(
            model_name="taskprogressnotification",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Aeroppp.manager",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 1, 13, 22, 11, 692206, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
